<?php

/**
 * @file
 * Source plugin for the Translation Management system that handles nodes.
 */

/**
 * Implements hook_tmgmt_source_plugin_info().
 */
function tmgmt_node_tmgmt_source_plugin_info() {
  $info['node'] = array(
    'label' => t('Node'),
    'description' => t('Source handler for nodes.'),
    'plugin controller class' => 'TMGMTNodeSourcePluginController',
    'ui controller class' => 'TMGMTNodeSourceUIController',
    'views controller class' => 'TMGMTNodeSourceViewsController',
    'item types' => array(),
  );
  foreach (node_type_get_names() as $type => $name) {
    if (translation_supported_type($type)) {
      $info['node']['item types'][$type] = $name;
    }
  }
  return $info;
}

/**
 * Updates a node translation.
 *
 * @param object $node
 *   The translated node object (the target).
 * @param array $translation
 *   An array with the structured translated data.
 *
 * @see TMGMTNodeSourcePluginController::getData()
 */
function tmgmt_node_update_node_translation($node, $translation, $language) {
  foreach ($translation as $name => $values) {
    // Special case for the node title.
    if ($name == 'node_title') {
      $node->title = $values['#text'];
      continue;
    }
    if (!is_array($values)) {
      continue;
    }
    tmgmt_field_populate_object($node, $language, $name, $values);
  }
  node_save($node);
}
