<?php

/**
 * @file
 * Module file of the translation management test module.
 */

/**
 * Implements hook_tmgmt_menu().
 */
function tmgmt_microsoft_test_menu() {
  $items['tmgmt_microsoft_mock/v2/Http.svc/Translate'] = array(
    'page callback' => 'tmgmt_microsoft_test_service_translate',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
  );
  $items['tmgmt_microsoft_mock/v2/Http.svc/GetLanguagesForTranslate'] = array(
    'page callback' => 'tmgmt_microsoft_test_service_get_languages',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Page callback for getting the supported languages.
 */
function tmgmt_microsoft_test_service_get_languages() {
  print '<ArrayOfstring xmlns="http://schemas.microsoft.com/2003/10/Serialization/Arrays" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><string>ar</string><string>bg</string><string>ca</string><string>zh-CHS</string><string>zh-CHT</string><string>cs</string><string>da</string><string>nl</string><string>en</string><string>et</string><string>fi</string><string>fr</string><string>de</string><string>el</string><string>ht</string><string>he</string><string>hi</string><string>hu</string><string>id</string><string>it</string><string>ja</string><string>ko</string><string>lv</string><string>lt</string><string>no</string><string>pl</string><string>pt</string><string>ro</string><string>ru</string><string>sk</string><string>sl</string><string>es</string><string>sv</string><string>th</string><string>tr</string><string>uk</string><string>vi</string></ArrayOfstring>';
}

/*
 * Page callback for getting the supported languages.
 */
function tmgmt_microsoft_test_service_translate() {
  if ($_GET['appId'] == 'correct key') {
    $translated_text = $_GET['to'] . '_' . $_GET['text'];
    print '<string xmlns="http://schemas.microsoft.com/2003/10/Serialization/">' . $translated_text . '</string>';

  }
  else {
    drupal_add_http_header('Status', '400 Invalid Key');
    print 'Wrong API Key';
  }
}

