<?php

/**
 * @file
 * Main module file for the Translation Management Source Field module.
 */

/**
 * Implements hook_tmgmt_source_translation_structure().
 *
 * This hook is implemented on behalf of the core text module.
 */
function text_tmgmt_source_translation_structure($field_name, $entity, $field_info, $field_instance, $job_item) {
  $job = tmgmt_job_load($job_item->tjid);
  $field_lang = field_language($job_item->item_type, $entity, $field_name);
  $structure = array();
  if (!empty($entity->{$field_name}[$field_lang])) {
    $structure['#label'] = check_plain($field_instance['label']);
    foreach ($entity->{$field_name}[$field_lang] as $delta => $value) {
      $structure[$delta]['#label'] = t('Delta #@delta', array('@delta' => $delta));
      $structure[$delta]['value'] = array(
        '#label' => $structure['#label'],
        '#text' => $value['value'],
        '#translate' => TRUE,
      );
      if ($field_info['type'] == 'text_with_summary' && !empty($value['summary'])) {
        $structure[$delta]['summary'] = array(
          '#label' => t('Summary'),
          '#text' => $value['summary'],
          '#translate' => TRUE,
        );
      }
    }
  }
  return $structure;
}

/**
 * Populates a field on an object with the provided field values.
 *
 * @param $object
 *   The object to be populated.
 * @param $language
 *   The field language.
 * @param $field_name
 *   The name of the field.
 * @param $values
 *   An array of values.
 */
function tmgmt_field_populate_object($object, $language, $field_name, $values) {
  $info = field_info_field($field_name);
  foreach ($values as $delta => $data) {
    $columns = array();
    foreach ($data as $column => $value) {
      $columns[$column] = $value['#text'];
    }
    $language = $info['translatable'] ? $language : LANGUAGE_NONE;
    // Make sure the array_merge() gets an array as a first parameter.
    if (!isset($object->{$field_name}[$language]) || !isset($object->{$field_name}[$language][$delta])) {
      $object->{$field_name}[$language][$delta] = array();
    }
    $object->{$field_name}[$language][$delta] = array_merge($object->{$field_name}[$language][$delta], $columns);
  }
}
